### ISSUE TITLE
Travis неправильно выполняет тест

### ISSUE THREAD

**Issue by nikitaodnorob** [czen/MMCS_CS311#64]
При сборке на Travis падает один из тестов со следующей ошибкой:
![image](https://user-images.githubusercontent.com/24944339/65361776-7e1c9a00-dc0d-11e9-9ea4-05618a9060d8.png)

Но тест требует именно 123.4, а не 1234.0, как сообщает Travis. Код из репозитория:
```csharp
DoubleLexer l = new DoubleLexer("123.4");
Assert.IsTrue(l.Parse(), "Не понимает 123.4");
Assert.AreEqual(l.ParseResult, 123.4, "Неправильно прочитал 123.4");
```

**Comment by czen** [comment]
@nikitaodnorob 
Я добавил tolerance=0.1 в Assert для этого теста
Проверьте, пожалуйста, работает это теперь в travis?

```
git remote add upstream https://github.com/czen/MMCS_CS311
git fetch upstream
git pull upstream master
git push origin
```

**Comment by nikitaodnorob** [comment]
Проблема остается
